//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 15/05/2014 11:02:14

namespace StrymonPresetStoreClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Presets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPreset> Presets
        {
            get
            {
                if ((this._Presets == null))
                {
                    this._Presets = base.CreateQuery<global::RITS.StrymonEditor.Models.DBPreset>("Presets");
                }
                return this._Presets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPreset> _Presets;
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBTag> Tags
        {
            get
            {
                if ((this._Tags == null))
                {
                    this._Tags = base.CreateQuery<global::RITS.StrymonEditor.Models.DBTag>("Tags");
                }
                return this._Tags;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBTag> _Tags;
        /// <summary>
        /// There are no comments for Parameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBParameter> Parameters
        {
            get
            {
                if ((this._Parameters == null))
                {
                    this._Parameters = base.CreateQuery<global::RITS.StrymonEditor.Models.DBParameter>("Parameters");
                }
                return this._Parameters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBParameter> _Parameters;
        /// <summary>
        /// There are no comments for PresetTags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPresetTag> PresetTags
        {
            get
            {
                if ((this._PresetTags == null))
                {
                    this._PresetTags = base.CreateQuery<global::RITS.StrymonEditor.Models.DBPresetTag>("PresetTags");
                }
                return this._PresetTags;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPresetTag> _PresetTags;
        /// <summary>
        /// There are no comments for Presets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToPresets(global::RITS.StrymonEditor.Models.DBPreset dBPreset)
        {
            base.AddObject("Presets", dBPreset);
        }
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToTags(global::RITS.StrymonEditor.Models.DBTag dBTag)
        {
            base.AddObject("Tags", dBTag);
        }
        /// <summary>
        /// There are no comments for Parameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToParameters(global::RITS.StrymonEditor.Models.DBParameter dBParameter)
        {
            base.AddObject("Parameters", dBParameter);
        }
        /// <summary>
        /// There are no comments for PresetTags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToPresetTags(global::RITS.StrymonEditor.Models.DBPresetTag dBPresetTag)
        {
            base.AddObject("PresetTags", dBPresetTag);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""RITS.StrymonEditor.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""DBPreset"">
        <Key>
          <PropertyRef Name=""PresetId"" />
        </Key>
        <Property Name=""PresetId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""PedalId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MachineId"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""PresetTags"" Type=""Collection(RITS.StrymonEditor.Models.DBPresetTag)"" />
        <NavigationProperty Name=""Parameters"" Type=""Collection(RITS.StrymonEditor.Models.DBParameter)"" />
      </EntityType>
      <EntityType Name=""DBTag"">
        <Key>
          <PropertyRef Name=""TagId"" />
        </Key>
        <Property Name=""TagId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""TagName"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""DBParameter"">
        <Key>
          <PropertyRef Name=""ParameterId"" />
        </Key>
        <Property Name=""ParameterId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PresetId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Value"" Type=""Edm.Int32"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""DBPresetTag"">
        <Key>
          <PropertyRef Name=""PresetTagId"" />
        </Key>
        <Property Name=""PresetTagId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Value"" Type=""Edm.String"" />
        <NavigationProperty Name=""Preset"" Type=""RITS.StrymonEditor.Models.DBPreset"" />
        <NavigationProperty Name=""Tag"" Type=""RITS.StrymonEditor.Models.DBTag"" />
      </EntityType>
      <ComplexType Name=""PresetMetadata"">
        <Property Name=""Tags"" Type=""Collection(RITS.StrymonEditor.Models.Tag)"" />
        <Property Name=""PresetId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PresetName"" Type=""Edm.String"" />
        <Property Name=""PedalId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MachineId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PedalName"" Type=""Edm.String"" />
        <Property Name=""MachineName"" Type=""Edm.String"" />
        <Property Name=""Author"" Type=""Edm.String"" />
      </ComplexType>
      <ComplexType Name=""Tag"">
        <Property Name=""TagName"" Type=""Edm.String"" />
        <Property Name=""Value"" Type=""Edm.String"" />
        <Property Name=""AvailableValues"" Type=""Collection(Edm.String)"" />
      </ComplexType>
      <ComplexType Name=""PresetSearch"">
        <Property Name=""PedalId"" Type=""Edm.Int32"" />
        <Property Name=""MachineId"" Type=""Edm.Int32"" />
        <Property Name=""Tags"" Type=""Collection(RITS.StrymonEditor.Models.Tag)"" />
      </ComplexType>
      <ComplexType Name=""StrymonXmlPreset"">
        <Property Name=""Pedal"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Machine"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""EPSet"" Type=""Collection(RITS.StrymonEditor.Models.HeelToeSetting)"" />
        <Property Name=""Parameters"" Type=""Collection(RITS.StrymonEditor.Models.XmlParameter)"" />
        <Property Name=""Tags"" Type=""Collection(RITS.StrymonEditor.Models.Tag)"" />
        <Property Name=""Name"" Type=""Edm.String"" />
      </ComplexType>
      <ComplexType Name=""HeelToeSetting"">
        <Property Name=""PotId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""HeelValue"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ToeValue"" Type=""Edm.Int32"" Nullable=""false"" />
      </ComplexType>
      <ComplexType Name=""XmlParameter"">
        <Property Name=""Value"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""FineValue"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
      </ComplexType>
    </Schema>
    <Schema Namespace=""System.Collections.Generic"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <ComplexType Name=""List_1OfPresetMetadata"">
        <Property Name=""Capacity"" Type=""Edm.Int32"" Nullable=""false"" />
      </ComplexType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Function Name=""GetSalesTaxRate"">
        <Parameter Name=""state"" Type=""Edm.String"" Unicode=""false"" />
        <ReturnType Type=""Edm.Double"" Nullable=""false"" />
      </Function>
      <Action Name=""SearchForPresets"">
        <Parameter Name=""criteria"" Type=""RITS.StrymonEditor.Models.PresetSearch"" />
        <ReturnType Type=""System.Collections.Generic.List_1OfPresetMetadata"" />
      </Action>
      <Action Name=""UploadPreset"">
        <Parameter Name=""uploadPreset"" Type=""RITS.StrymonEditor.Models.StrymonXmlPreset"" />
      </Action>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Presets"" EntityType=""RITS.StrymonEditor.Models.DBPreset"">
          <NavigationPropertyBinding Path=""PresetTags"" Target=""PresetTags"" />
          <NavigationPropertyBinding Path=""Parameters"" Target=""Parameters"" />
        </EntitySet>
        <EntitySet Name=""Tags"" EntityType=""RITS.StrymonEditor.Models.DBTag"" />
        <EntitySet Name=""Parameters"" EntityType=""RITS.StrymonEditor.Models.DBParameter"" />
        <EntitySet Name=""PresetTags"" EntityType=""RITS.StrymonEditor.Models.DBPresetTag"">
          <NavigationPropertyBinding Path=""Preset"" Target=""Presets"" />
          <NavigationPropertyBinding Path=""Tag"" Target=""Tags"" />
        </EntitySet>
        <FunctionImport Name=""GetSalesTaxRate"" Function=""Default.GetSalesTaxRate"" IncludeInServiceDocument=""true"" />
        <ActionImport Name=""SearchForPresets"" Action=""Default.SearchForPresets"" />
        <ActionImport Name=""UploadPreset"" Action=""Default.UploadPreset"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
