//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 30/07/2014 11:52:30
namespace StrymonPresetStoreClient.RITS.StrymonEditor.Models
{
    /// <summary>
    /// There are no comments for DBPreset in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PresetId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PresetId")]
    public partial class DBPreset : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DBPreset object.
        /// </summary>
        /// <param name="presetId">Initial value of PresetId.</param>
        /// <param name="pedalId">Initial value of PedalId.</param>
        /// <param name="machineId">Initial value of MachineId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public static DBPreset CreateDBPreset(int presetId, int pedalId, int machineId)
        {
            DBPreset dBPreset = new DBPreset();
            dBPreset.PresetId = presetId;
            dBPreset.PedalId = pedalId;
            dBPreset.MachineId = machineId;
            return dBPreset;
        }
        /// <summary>
        /// There are no comments for Property PresetId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int PresetId
        {
            get
            {
                return this._PresetId;
            }
            set
            {
                this.OnPresetIdChanging(value);
                this._PresetId = value;
                this.OnPresetIdChanged();
                this.OnPropertyChanged("PresetId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _PresetId;
        partial void OnPresetIdChanging(int value);
        partial void OnPresetIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PedalId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int PedalId
        {
            get
            {
                return this._PedalId;
            }
            set
            {
                this.OnPedalIdChanging(value);
                this._PedalId = value;
                this.OnPedalIdChanged();
                this.OnPropertyChanged("PedalId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _PedalId;
        partial void OnPedalIdChanging(int value);
        partial void OnPedalIdChanged();
        /// <summary>
        /// There are no comments for Property MachineId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int MachineId
        {
            get
            {
                return this._MachineId;
            }
            set
            {
                this.OnMachineIdChanging(value);
                this._MachineId = value;
                this.OnMachineIdChanged();
                this.OnPropertyChanged("MachineId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _MachineId;
        partial void OnMachineIdChanging(int value);
        partial void OnMachineIdChanged();
        /// <summary>
        /// There are no comments for Property PresetTags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBPresetTag> PresetTags
        {
            get
            {
                return this._PresetTags;
            }
            set
            {
                this.OnPresetTagsChanging(value);
                this._PresetTags = value;
                this.OnPresetTagsChanged();
                this.OnPropertyChanged("PresetTags");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBPresetTag> _PresetTags = new global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBPresetTag>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnPresetTagsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBPresetTag> value);
        partial void OnPresetTagsChanged();
        /// <summary>
        /// There are no comments for Property Parameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBParameter> Parameters
        {
            get
            {
                return this._Parameters;
            }
            set
            {
                this.OnParametersChanging(value);
                this._Parameters = value;
                this.OnParametersChanged();
                this.OnPropertyChanged("Parameters");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBParameter> _Parameters = new global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBParameter>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnParametersChanging(global::Microsoft.OData.Client.DataServiceCollection<global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBParameter> value);
        partial void OnParametersChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DBTag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TagId")]
    public partial class DBTag : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DBTag object.
        /// </summary>
        /// <param name="tagId">Initial value of TagId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public static DBTag CreateDBTag(int tagId)
        {
            DBTag dBTag = new DBTag();
            dBTag.TagId = tagId;
            return dBTag;
        }
        /// <summary>
        /// There are no comments for Property TagId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int TagId
        {
            get
            {
                return this._TagId;
            }
            set
            {
                this.OnTagIdChanging(value);
                this._TagId = value;
                this.OnTagIdChanged();
                this.OnPropertyChanged("TagId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _TagId;
        partial void OnTagIdChanging(int value);
        partial void OnTagIdChanged();
        /// <summary>
        /// There are no comments for Property TagName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public string TagName
        {
            get
            {
                return this._TagName;
            }
            set
            {
                this.OnTagNameChanging(value);
                this._TagName = value;
                this.OnTagNameChanged();
                this.OnPropertyChanged("TagName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private string _TagName;
        partial void OnTagNameChanging(string value);
        partial void OnTagNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DBParameter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ParameterId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ParameterId")]
    public partial class DBParameter : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DBParameter object.
        /// </summary>
        /// <param name="parameterId">Initial value of ParameterId.</param>
        /// <param name="presetId">Initial value of PresetId.</param>
        /// <param name="value">Initial value of Value.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public static DBParameter CreateDBParameter(int parameterId, int presetId, int value)
        {
            DBParameter dBParameter = new DBParameter();
            dBParameter.ParameterId = parameterId;
            dBParameter.PresetId = presetId;
            dBParameter.Value = value;
            return dBParameter;
        }
        /// <summary>
        /// There are no comments for Property ParameterId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int ParameterId
        {
            get
            {
                return this._ParameterId;
            }
            set
            {
                this.OnParameterIdChanging(value);
                this._ParameterId = value;
                this.OnParameterIdChanged();
                this.OnPropertyChanged("ParameterId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _ParameterId;
        partial void OnParameterIdChanging(int value);
        partial void OnParameterIdChanged();
        /// <summary>
        /// There are no comments for Property PresetId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int PresetId
        {
            get
            {
                return this._PresetId;
            }
            set
            {
                this.OnPresetIdChanging(value);
                this._PresetId = value;
                this.OnPresetIdChanged();
                this.OnPropertyChanged("PresetId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _PresetId;
        partial void OnPresetIdChanging(int value);
        partial void OnPresetIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _Value;
        partial void OnValueChanging(int value);
        partial void OnValueChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DBPresetTag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PresetTagId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PresetTagId")]
    public partial class DBPresetTag : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DBPresetTag object.
        /// </summary>
        /// <param name="presetTagId">Initial value of PresetTagId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public static DBPresetTag CreateDBPresetTag(int presetTagId)
        {
            DBPresetTag dBPresetTag = new DBPresetTag();
            dBPresetTag.PresetTagId = presetTagId;
            return dBPresetTag;
        }
        /// <summary>
        /// There are no comments for Property PresetTagId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public int PresetTagId
        {
            get
            {
                return this._PresetTagId;
            }
            set
            {
                this.OnPresetTagIdChanging(value);
                this._PresetTagId = value;
                this.OnPresetTagIdChanged();
                this.OnPropertyChanged("PresetTagId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private int _PresetTagId;
        partial void OnPresetTagIdChanging(int value);
        partial void OnPresetTagIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Preset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBPreset Preset
        {
            get
            {
                return this._Preset;
            }
            set
            {
                this.OnPresetChanging(value);
                this._Preset = value;
                this.OnPresetChanged();
                this.OnPropertyChanged("Preset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBPreset _Preset;
        partial void OnPresetChanging(global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBPreset value);
        partial void OnPresetChanged();
        /// <summary>
        /// There are no comments for Property Tag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBTag Tag
        {
            get
            {
                return this._Tag;
            }
            set
            {
                this.OnTagChanging(value);
                this._Tag = value;
                this.OnTagChanged();
                this.OnPropertyChanged("Tag");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBTag _Tag;
        partial void OnTagChanging(global::StrymonPresetStoreClient.RITS.StrymonEditor.Models.DBTag value);
        partial void OnTagChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }

}
namespace StrymonPresetStoreClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "System.Collections.Generic", "StrymonPresetStoreClient.System.Collections.Generic");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "RITS.StrymonEditor.Models", "StrymonPresetStoreClient.RITS.StrymonEditor.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "StrymonPresetStoreClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("StrymonPresetStoreClient.System.Collections.Generic", global::System.StringComparison.Ordinal))
            {
                return string.Concat("System.Collections.Generic.", clientType.Name);
            }
            if (clientType.Namespace.Equals("StrymonPresetStoreClient.RITS.StrymonEditor.Models", global::System.StringComparison.Ordinal))
            {
                return string.Concat("RITS.StrymonEditor.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("StrymonPresetStoreClient.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Presets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPreset> Presets
        {
            get
            {
                if ((this._Presets == null))
                {
                    this._Presets = base.CreateQuery<global::RITS.StrymonEditor.Models.DBPreset>("Presets");
                }
                return this._Presets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPreset> _Presets;
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBTag> Tags
        {
            get
            {
                if ((this._Tags == null))
                {
                    this._Tags = base.CreateQuery<global::RITS.StrymonEditor.Models.DBTag>("Tags");
                }
                return this._Tags;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBTag> _Tags;
        /// <summary>
        /// There are no comments for Parameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBParameter> Parameters
        {
            get
            {
                if ((this._Parameters == null))
                {
                    this._Parameters = base.CreateQuery<global::RITS.StrymonEditor.Models.DBParameter>("Parameters");
                }
                return this._Parameters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBParameter> _Parameters;
        /// <summary>
        /// There are no comments for PresetTags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPresetTag> PresetTags
        {
            get
            {
                if ((this._PresetTags == null))
                {
                    this._PresetTags = base.CreateQuery<global::RITS.StrymonEditor.Models.DBPresetTag>("PresetTags");
                }
                return this._PresetTags;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RITS.StrymonEditor.Models.DBPresetTag> _PresetTags;
        /// <summary>
        /// There are no comments for Presets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToPresets(global::RITS.StrymonEditor.Models.DBPreset dBPreset)
        {
            base.AddObject("Presets", dBPreset);
        }
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToTags(global::RITS.StrymonEditor.Models.DBTag dBTag)
        {
            base.AddObject("Tags", dBTag);
        }
        /// <summary>
        /// There are no comments for Parameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToParameters(global::RITS.StrymonEditor.Models.DBParameter dBParameter)
        {
            base.AddObject("Parameters", dBParameter);
        }
        /// <summary>
        /// There are no comments for PresetTags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        public void AddToPresetTags(global::RITS.StrymonEditor.Models.DBPresetTag dBPresetTag)
        {
            base.AddObject("PresetTags", dBPresetTag);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""RITS.StrymonEditor.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""DBPreset"">
        <Key>
          <PropertyRef Name=""PresetId"" />
        </Key>
        <Property Name=""PresetId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""PedalId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MachineId"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""PresetTags"" Type=""Collection(RITS.StrymonEditor.Models.DBPresetTag)"" />
        <NavigationProperty Name=""Parameters"" Type=""Collection(RITS.StrymonEditor.Models.DBParameter)"" />
      </EntityType>
      <EntityType Name=""DBTag"">
        <Key>
          <PropertyRef Name=""TagId"" />
        </Key>
        <Property Name=""TagId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""TagName"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""DBParameter"">
        <Key>
          <PropertyRef Name=""ParameterId"" />
        </Key>
        <Property Name=""ParameterId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PresetId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Value"" Type=""Edm.Int32"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""DBPresetTag"">
        <Key>
          <PropertyRef Name=""PresetTagId"" />
        </Key>
        <Property Name=""PresetTagId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Value"" Type=""Edm.String"" />
        <NavigationProperty Name=""Preset"" Type=""RITS.StrymonEditor.Models.DBPreset"" />
        <NavigationProperty Name=""Tag"" Type=""RITS.StrymonEditor.Models.DBTag"" />
      </EntityType>
      <ComplexType Name=""PresetMetadata"">
        <Property Name=""Tags"" Type=""Collection(RITS.StrymonEditor.Models.Tag)"" />
        <Property Name=""PresetId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PresetName"" Type=""Edm.String"" />
        <Property Name=""PedalId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MachineId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PedalName"" Type=""Edm.String"" />
        <Property Name=""MachineName"" Type=""Edm.String"" />
        <Property Name=""Author"" Type=""Edm.String"" />
      </ComplexType>
      <ComplexType Name=""Tag"">
        <Property Name=""TagName"" Type=""Edm.String"" />
        <Property Name=""Value"" Type=""Edm.String"" />
        <Property Name=""AvailableValues"" Type=""Collection(Edm.String)"" />
      </ComplexType>
      <ComplexType Name=""PresetSearch"">
        <Property Name=""PedalId"" Type=""Edm.Int32"" />
        <Property Name=""MachineId"" Type=""Edm.Int32"" />
        <Property Name=""Tags"" Type=""Collection(RITS.StrymonEditor.Models.Tag)"" />
      </ComplexType>
      <ComplexType Name=""StrymonXmlPreset"">
        <Property Name=""Pedal"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Machine"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""EPSet"" Type=""Collection(RITS.StrymonEditor.Models.HeelToeSetting)"" />
        <Property Name=""Parameters"" Type=""Collection(RITS.StrymonEditor.Models.XmlParameter)"" />
        <Property Name=""Tags"" Type=""Collection(RITS.StrymonEditor.Models.Tag)"" />
        <Property Name=""Name"" Type=""Edm.String"" />
      </ComplexType>
      <ComplexType Name=""HeelToeSetting"">
        <Property Name=""PotId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""HeelValue"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ToeValue"" Type=""Edm.Int32"" Nullable=""false"" />
      </ComplexType>
      <ComplexType Name=""XmlParameter"">
        <Property Name=""Value"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""FineValue"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
      </ComplexType>
    </Schema>
    <Schema Namespace=""System.Collections.Generic"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <ComplexType Name=""List_1OfPresetMetadata"">
        <Property Name=""Capacity"" Type=""Edm.Int32"" Nullable=""false"" />
      </ComplexType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Function Name=""GetSalesTaxRate"">
        <Parameter Name=""state"" Type=""Edm.String"" Unicode=""false"" />
        <ReturnType Type=""Edm.Double"" Nullable=""false"" />
      </Function>
      <Action Name=""SearchForPresets"">
        <Parameter Name=""criteria"" Type=""RITS.StrymonEditor.Models.PresetSearch"" />
        <ReturnType Type=""System.Collections.Generic.List_1OfPresetMetadata"" />
      </Action>
      <Action Name=""UploadPreset"">
        <Parameter Name=""uploadPreset"" Type=""RITS.StrymonEditor.Models.StrymonXmlPreset"" />
      </Action>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Presets"" EntityType=""RITS.StrymonEditor.Models.DBPreset"">
          <NavigationPropertyBinding Path=""PresetTags"" Target=""PresetTags"" />
          <NavigationPropertyBinding Path=""Parameters"" Target=""Parameters"" />
        </EntitySet>
        <EntitySet Name=""Tags"" EntityType=""RITS.StrymonEditor.Models.DBTag"" />
        <EntitySet Name=""Parameters"" EntityType=""RITS.StrymonEditor.Models.DBParameter"" />
        <EntitySet Name=""PresetTags"" EntityType=""RITS.StrymonEditor.Models.DBPresetTag"">
          <NavigationPropertyBinding Path=""Preset"" Target=""Presets"" />
          <NavigationPropertyBinding Path=""Tag"" Target=""Tags"" />
        </EntitySet>
        <FunctionImport Name=""GetSalesTaxRate"" Function=""Default.GetSalesTaxRate"" IncludeInServiceDocument=""true"" />
        <ActionImport Name=""SearchForPresets"" Action=""Default.SearchForPresets"" />
        <ActionImport Name=""UploadPreset"" Action=""Default.UploadPreset"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
